apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: first-workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say Howdy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Howdy Eric and Robert... amazing job you guys!"
  ci-job:
    needs:
      - build
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Build Go app
        uses: docker://golang:1.20
        run: |
          go build -v ./...
      - name: Run tests
        uses: docker://golang:1.20
        run: |
          go test -v ./...